TheMoroccanDemonlist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from level import views as level_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', level_views.classic_mainlist, name='home'),
    path('player/', include('player.urls')),
    path('levels/', include('level.urls')),
    path('submit/', include('recordsubmission.urls')),
    path('guidelines/', views.guidelines, name='guidelines'),
]

level/urls.py
from django.urls import path
from . import views

app_name = 'level'

urlpatterns = [
    path('<int:pk>/', views.detail, name='classic_level_detail'),
    path('classic-mainlist/', views.classic_mainlist, name='classic_mainlist'),
    path('classic-extendedlist/', views.classic_extendedlist, name='classic_extendedlist'),
    path('classic-legacylist/', views.classic_legacylist, name='classic_legacylist'),
    path('classic-stat-viewer/', views.classic_stat_viewer, name='classic_statviewer'),
    path('platformer-mainlist/', views.platformer_mainlist, name='platformer_mainlist'),
    path('platformer-stat-viewer/', views.platformer_stat_viewer, name='platformer_statviewer'),
    path('search/', views.search, name='search'),
]

player/urls.py
from django.urls import path
from . import views

app_name = 'player'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('verify-email/', views.verify_email, name='verify-email'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('edit-social-platforms/', views.edit_social_platforms, name='edit_social_platforms'),
    path('search/', views.search, name='search'),
]

player/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from region.models import Region
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class PlayerManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set.")
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(username, email, password, **extra_fields)

class Player(AbstractBaseUser, PermissionsMixin):
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_email_verified = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=255, unique=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)
    classic_points = models.FloatField(default=0)
    platformer_points = models.FloatField(default=0)
    discord = models.CharField(max_length=255, blank=True, null=True)
    twitter = models.URLField(max_length=255, blank=True, null=True)
    youtube = models.URLField(max_length=255, blank=True, null=True)
    twitch = models.URLField(max_length=255, blank=True, null=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = PlayerManager()

    def __str__(self):
        return self.username
    
@receiver(post_save, sender=Player)
def update_player_classic_points(sender, instance, created, **kwargs):
    if not created:
        player = instance
        
        total_classic_points = 0

        for level_record in player.classiclevelrecord_set.all():
            level = level_record.level
            record_percentage = level_record.record_percentage

            if record_percentage == 100:
                total_classic_points += level.points
            else:
                total_classic_points += level.points * 1/3

        if player.classic_points != total_classic_points:
            player.classic_points = total_classic_points
            player.save(update_fields=['classic_points'])

@receiver(post_save, sender=Player)
def update_player_platformer_points(sender, instance, created, **kwargs):
    if not created:
        player = instance
        
        total_platformer_points = 0

        for level_record in player.platformerlevelrecord_set.all():
            level = level_record.level
            total_platformer_points += level.points

        if player.platformer_points != total_platformer_points:
            player.platformer_points = total_platformer_points
            player.save(update_fields=['platformer_points'])

@receiver(post_save, sender=Player)
def update_region_classic_points(sender, instance, created, **kwargs):
    if not created:
        region = instance.region
        region.classic_points = region.calculate_classic_points()
        if region.classic_points == None:
            region.classic_points = 0
        region.save()

@receiver(post_save, sender=Player)
def update_region_platformer_points(sender, instance, created, **kwargs):
    if not created:
        region = instance.region
        region.platformer_points = region.calculate_platformer_points()
        if region.platformer_points == None:
            region.platformer_points = 0
        region.save()

player/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Player
from region.models import Region
from django_recaptcha.fields import ReCaptchaField
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.forms import SetPasswordForm

class PlayerCreationForm(UserCreationForm):
    captcha = ReCaptchaField()
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'email',
    }))
    region = forms.ModelChoiceField(queryset=Region.objects.all(), required=True, widget=forms.Select(attrs={
        'class': 'form-control',
        'id': 'region',
    }))

    class Meta:
        model = Player
        fields = ('username', 'email', 'region', 'password1', 'password2')

class LoginForm(forms.Form):
    captcha = ReCaptchaField()
    username = forms.CharField(max_length=255, required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'username',
            'placeholder': 'Username'
        })
    )
    password = forms.CharField(required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'password',
            'placeholder': 'Password'
        })
    )

    class Meta:
        model = Player
        fields = ('username', 'password')

class CustomPasswordResetForm(PasswordResetForm):
    captcha = ReCaptchaField()

class CustomPasswordResetConfirmForm(SetPasswordForm):
    captcha = ReCaptchaField()

class SocialPlatformForm(forms.ModelForm):
    discord = forms.CharField(max_length=255, required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'discord',
            'placeholder': 'Your Discord username'
        })
    )
    youtube = forms.CharField(max_length=255, required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'youtube',
            'placeholder': 'Your YouTube channel'
        })
    )
    twitch = forms.CharField(max_length=255, required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'twitch',
            'placeholder': 'Your Twitch channel'
        })
    )
    twitter = forms.CharField(max_length=255, required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'twitter',
            'placeholder': 'Your Twitter profile'
        })
    )
    class Meta:
        model = Player
        fields = ['discord', 'youtube', 'twitch', 'twitter']

class PlayerSearchForm(forms.Form):
    query = forms.CharField(max_length=255)

player/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.messages.views import SuccessMessageMixin
from .models import Player
from .forms import PlayerCreationForm, LoginForm, CustomPasswordResetForm, CustomPasswordResetConfirmForm, SocialPlatformForm, PlayerSearchForm
from levelrecord.models import ClassicLevelRecord
from django.db.models import Q
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.urls import reverse_lazy, reverse
from .tokens import account_activation_token

# Create your views here.

def login_user(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username=form.cleaned_data['username']
                password=form.cleaned_data['password']
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect("home")
                else:
                    messages.error(request, ("Incorrect credentials. Please try again."))
        else:
            form = LoginForm()

        return render(request, 'player/authentication.html', {'form': form})
    
def logout_user(request):
    logout(request)
    messages.success(request, ("You were logged out."))
    
    return redirect("player:login")

def register_user(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        if request.method == "POST":
            form = PlayerCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                user = authenticate(username=username, password=password)
                login(request, user)
                messages.success(request, ("Registration successful. An email has been sent with instructions to verify your account. Check your SPAM folder if you don't see it in your inbox."))
                return redirect("player:verify-email")
        else:
            form = PlayerCreationForm()

        return render(request, 'player/authentication.html', {'form': form})

def verify_email(request):
    if not request.user.is_email_verified:
        current_site = get_current_site(request)
        user = request.user
        email = request.user.email
        subject = "Verify your email"
        message = render_to_string('player/emailbody.html', {
            'request': request,
            'user': user,
            'domain': current_site.domain,
            'uid':urlsafe_base64_encode(force_bytes(user.pk)),
            'token':account_activation_token.make_token(user),
        })
        email = EmailMessage(
            subject, message, to=[email]
        )
        email.content_subtype = 'html'
        email.send()
        return redirect('player:profile', username=request.user.username)
    else:
        return redirect('player:profile', username=request.user.username)

def verify_email_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Player.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Player.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_email_verified = True
        user.save()
        messages.success(request, 'Your email has been verified.')
        return redirect('player:profile', username=request.user.username)  
    else:
        messages.warning(request, 'The link is invalid.')
    return redirect('player:profile', username=request.user.username)

class CustomPasswordResetView(SuccessMessageMixin, PasswordResetView):
    form_class = CustomPasswordResetForm
    template_name = 'player/passwordreset.html'
    email_template_name = 'player/passwordresetbody.html'
    success_url = reverse_lazy('player:password_reset_done')

class CustomPasswordResetDoneView(PasswordResetDoneView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "We have emailed you instructions for setting your password. If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.")
        return redirect('player:login')

class CustomPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    form_class = CustomPasswordResetConfirmForm
    template_name = 'player/passwordresetconfirm.html'
    success_url = reverse_lazy('player:password_reset_complete')
    success_message = "Your password has been set. You can now log in with the new password."

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "Your password has been set. You can now log in with the new password.")
        return redirect('player:login')

def profile(request, username):
    player = Player.objects.get(username=username)
    staff_members = Player.objects.filter(is_staff=True)

    player_ranking = Player.objects.filter(classic_points__gt=player.classic_points).count() + 1
    completed_levels = ClassicLevelRecord.objects.filter(player=player, level__ranking__lte=150)
    hardest_level = completed_levels.order_by('level__ranking').first()
    first_victors = [record for record in completed_levels if record.level.first_victor == player]
    level_counts = {
      'main': completed_levels.filter(level__ranking__lte=75).count(),
      'extended': completed_levels.filter(Q(level__ranking__gt=75) & Q(level__ranking__lte=150)).count(),
      'legacy': completed_levels.filter(level__ranking__gt=150).count()
    }

    context = {
        'player': player,
        'player_ranking': player_ranking,
        'completed_levels': completed_levels,
        'hardest_level': hardest_level,
        'first_victors': first_victors,
        'level_counts': level_counts,
        'staff_members': staff_members
    }
    return render(request, 'player/profile.html', context)

@login_required
def edit_social_platforms(request):
    social_form = SocialPlatformForm(initial={'discord': request.user.discord, 'youtube': request.user.youtube, 'twitch': request.user.twitch, 'twitter': request.user.twitter})
    if request.method == 'POST':
        form = SocialPlatformForm(request.POST)
        if form.is_valid():
            player = Player.objects.get(pk=request.user.pk)
            player.discord = form.cleaned_data['discord']
            player.youtube = form.cleaned_data['youtube']
            player.twitch = form.cleaned_data['twitch']
            player.twitter = form.cleaned_data['twitter']
            player.save()
            return redirect('player:profile', username=request.user.username)
        else:
            messages.error(request, "Invalid form. Please enter valid URLs.")
            return redirect('player:profile', username=request.user.username)
        
    return render(request, 'player/profile.html', {'social_form': social_form})

def search(request):
    staff_members = Player.objects.filter(is_staff=True)
    if request.method == 'POST':
        form = PlayerSearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            players = Player.objects.filter(username__icontains=query)
            if len(players) == 1:
                player = players[0]
                if isinstance(player, Player):
                    return redirect(reverse('player:profile', args=[player.username]))
            elif len(players) == 0:
                messages.error(request, ("No player found. Please try again."))
                return redirect("player:profile", username=request.user.username)
            else:
                context = {
                    'players': players,
                    'staff_members': staff_members
                }
                return render(request, 'player/search.html', context)
        else:
            form = PlayerSearchForm()
            return render(request, 'player/search.html', {'form': form, 'staff_members': staff_members})

templates/player/emailbody.html
<div>
    <p>You're receiving this email because you created an account at <a href="{{ request.scheme }}://{{ domain }}">{{ domain }}</a>.</p>
    <p>Please click on the following link to verify your email address:</p>
    <p><a href="{{ request.scheme }}://{{ domain }}{% url 'player:verify-email-confirm' uidb64=uid token=token %}">{{ request.scheme }}://{{ domain }}{% url 'player:verify-email-confirm' uidb64=uid token=token %}</a></p>
    <p>Thanks for using our site!</p>
    <p>TheMoroccanDemonlist team</p>
</div>

templates/player/passwordreset.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="{{ form.email.id_for_label }}" class="form-label">Email address</label>
      <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.html_name }}" aria-describedby="{{ form.email.id_for_label }}_help">
      <div id="{{ form.email.id_for_label }}_help" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="col-md-6 mb-3">
        {{ form.captcha }} 
    </div>
    <button type="submit" class="btn btn-primary">Reset my password</button>
  </form>
</div>
{% endblock %}

templates/player/passwordresetbody.html
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
Please go to the following page and choose a new password:

{{ protocol }}://{{ domain }}{% url 'player:password_reset_confirm' uidb64=uid token=token %}

Your username, in case you’ve forgotten: {{ user.get_username }}
Thanks for using our site!
{{ site_name }} team

templates/player/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ player.username }}'s Profile{% endblock %}
{% block content %}
<div class="container">
  {% if not player.is_email_verified and request.user == player %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      Please verify your email for a full account experience.
      <a href="{% url 'player:verify-email' %}" class="alert-link">Resend email.</a>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}

  <div class="row mb-4">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h1 class="card-title">{{ player.username }} - #{{ player_ranking }}</h1>
              <ul class="list-group list-group-horizontal mt-2">
                <li class="list-unstyled">
                  {% if player.discord %}
                    <a class="text-decoration-none">
                      <img src="{% static 'images/discord.png' %}" style="width:32px;" alt="Discord Icon" class="discord-icon me-1">
                    </a>
                  {% endif %}
                </li>
                <li class="list-unstyled">
                  {% if player.youtube %}
                    <a href="{{ player.youtube }}" target="_blank" class="text-decoration-none">
                      <img src="{% static 'images/youtube.png' %}" style="width:32px;" alt="YouTube Icon" class="youtube-icon me-1">
                    </a>
                  {% endif %}
                </li>
                <li class="list-unstyled">
                  {% if player.twitch %}
                    <a href="{{ player.twitch }}" target="_blank" class="text-decoration-none">
                      <img src="{% static 'images/twitch.png' %}" style="width:32px;" alt="Twitch Icon" class="twitch-icon me-1">
                    </a>
                  {% endif %}
                </li>
                <li class="list-unstyled">
                  {% if player.twitter %}
                    <a href="{{ player.twitter }}" target="_blank" class="text-decoration-none">
                      <img src="{% static 'images/twitter.png' %}" style="width:32px;" alt="Twitter Icon" class="twitter-icon me-1">
                    </a>
                  {% endif %}
                </li>
                <li class="list-unstyled">
                    {% if player == request.user %}
                    <a href="" data-bs-toggle="modal" data-bs-target="#socialModal" class="text-decoration-none ms-3">
                        <img src="{% static 'images/pencil.png' %}" style="width:32px;" alt="Pencil Icon" class="twitter-icon me-1">
                    </a>
                    {% endif %}
                </li>
              </ul>
            </div>
            <div class="col-md-6">
                <form class="d-flex" role="search" method="post" action="{% url 'player:search' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search for a player" aria-label="Search" name="query">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
            <div class="col-md-6">
              <div class="modal fade" id="socialModal" tabindex="-1" aria-labelledby="socialModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="socialModalLabel">Edit My Socials</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <form method="post" action="{% url 'player:edit_social_platforms' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="discordInput" class="form-label">Discord</label>
                            {% if player.discord %}
                            <input type="text" class="form-control" id="discordInput" name="discord" value="{{ player.discord }}" placeholder="@username">
                            {% else %}
                            <input type="text" class="form-control" id="discordInput" name="discord" placeholder="@username">
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="youtubeInput" class="form-label">YouTube</label>
                            {% if player.youtube %}
                            <input type="text" class="form-control" id="youtubeInput" name="youtube" value="{{ player.youtube }}" placeholder="@username">
                            {% else %}
                            <input type="text" class="form-control" id="youtubeInput" name="youtube" placeholder="https://www.youtube.com/channel/username">
                            {% endif %}
                          </div>
                          <div class="mb-3">
                            <label for="twitchInput" class="form-label">Twitch</label>
                            {% if player.twitch %}
                            <input type="text" class="form-control" id="twitchInput" name="twitch" value="{{ player.twitch }}" placeholder="@username">
                            {% else %}
                            <input type="text" class="form-control" id="twitchInput" name="twitch" placeholder="https://www.twitch.tv/username">
                            {% endif %}
                          </div>
                          <div class="mb-3">
                            <label for="twitterInput" class="form-label">Twitter</label>
                            {% if player.twitter %}
                            <input type="text" class="form-control" id="twitterInput" name="twitter" value="{{ player.twitter }}" placeholder="@username">
                            {% else %}
                            <input type="text" class="form-control" id="twitterInput" name="twitter" placeholder="https://twitter.com/username">
                            {% endif %}
                          </div>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col-sm-6">
              <h2 class="card-title">Hardest Level:</h2>
              {% if hardest_level %}
              <a href="{% url 'level:classic_level_detail' hardest_level.level.id %}" class="btn btn-outline-primary btn-lg me-2 mb-2">{{ hardest_level.level.name }}</a>
                {% else %}
                <a class="btn btn-outline-primary btn-lg me-2 mb-2">No hardest level found</a>
                {% endif %}
            </div>
            <div class="col-sm-6">
              <h2 class="card-title">Levels Count:</h2>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Main: {{ level_counts.main }}</li>
                <li class="list-group-item">Extended: {{ level_counts.extended }}</li>
                <li class="list-group-item">Legacy: {{ level_counts.legacy }}</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

        <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">Completed levels:</h2>
          <div class="d-flex flex-wrap">
            {% if completed_levels %}
            {% for record in completed_levels %}
              <a href="{% url 'level:classic_level_detail' record.level.id %}" class="btn btn-outline-primary btn-lg me-2 mb-2">{{ record.level.name }}</a>
            {% endfor %}
            {% else %}
              <a class="btn btn-outline-primary btn-lg me-2 mb-2">No completed levels found</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">First victor in:</h2>
          <div class="d-flex flex-wrap">
            {% if first_victors %}
            {% for record in first_victors %}
              <a href="{% url 'level:classic_level_detail' record.level.id %}" class="btn btn-outline-primary btn-lg me-2 mb-2">{{ record.level.name }}</a>
            {% endfor %}
            {% else %}
              <a class="btn btn-outline-primary btn-lg me-2 mb-2">No first victor levels found</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      {% if player == request.user %}
      <div class="card mb-3">
        <div class="card-header text-center">
            <h3>Settings</h3>
        </div>
        <div class="card-body text-center">
          <p class="text-start">Want to change your password? Click the button below and you will be redirected to the change password form.</p>
          <a href="{% url 'player:password_reset' %}" class="btn btn-primary w-75">Change Password</a>
        </div>
        <hr>
        <div class="card-body">
          <p>Select the theme you would like to use.</p>
          <div class="form-check form-switch">
            <input class="form-check-input" type="radio" name="theme" id="lightTheme" value="light" checked>
            <label class="form-check-label" for="lightTheme">Light</label>
          </div>
          <div class="form-check form-switch">
              <input class="form-check-input" type="radio" name="theme" id="darkTheme" value="dark">
              <label class="form-check-label" for="darkTheme">Dark</label>
          </div>
        </div>
    </div>
      {% endif %}
        <div class="card">
            <div class="card-header text-center">
                <h3>List editors</h3>
            </div>
            <div class="card-body text-center">
                <p>Contact any of these people if you need assistance regarding the list.</p>
                {% for staff_member in staff_members %}
                    <a style="color: inherit;" class="text-decoration-none fw-bold" href="{% url 'player:profile' staff_member.username %}">{{ staff_member }}</a>{% if not forloop.last %} - {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header text-center">
                <h3>Guidelines</h3>
            </div>
            <div class="card-body text-center">
                <p>Before any submission please consider checking the guidelines for the list. Any submission that does not follow the guidelines will be rejected.</p>
                <a href="{% url 'guidelines' %}" class="btn btn-primary w-75">Read the guidelines</a>
            </div>
        </div>

        <div class="card mt-3">
            <iframe src="https://discord.com/widget?id=1144377634831220847&theme=dark" class="w-100" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
        </div>
    </div>
  </div>
</div>
{% endblock %}