TheMoroccanDemonlist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from level import views as level_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', level_views.classic_mainlist, name='home'),
    path('player/', include('player.urls')),
    path('levels/', include('level.urls')),
    path('submit/', include('recordsubmission.urls')),
    path('guidelines/', views.guidelines, name='guidelines'),
]

level/urls.py
from django.urls import path
from . import views

app_name = 'level'

urlpatterns = [
    path('<int:pk>/', views.detail, name='classic_level_detail'),
    path('classic-mainlist/', views.classic_mainlist, name='classic_mainlist'),
    path('classic-extendedlist/', views.classic_extendedlist, name='classic_extendedlist'),
    path('classic-legacylist/', views.classic_legacylist, name='classic_legacylist'),
    path('classic-stat-viewer/', views.classic_stat_viewer, name='classic_statviewer'),
    path('platformer-mainlist/', views.platformer_mainlist, name='platformer_mainlist'),
    path('platformer-stat-viewer/', views.platformer_stat_viewer, name='platformer_statviewer'),
    path('search/', views.search, name='search'),
]

recordsubmission/urls.py
from django.urls import path
from . import views

app_name = 'recordsubmission'

urlpatterns = [
    path('submit-record/<str:record_type>/', views.submit_record, name='submit_record'),
    path('submissions/', views.submissions, name='submissions'),
]

recordsubmission/models.py
from django.db import models
from player.models import Player
from level.models import ClassicLevel, PlatformerLevel
from django.core.validators import MaxValueValidator
from datetime import timedelta
import uuid

# Create your models here.

class RecordSubmission(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected'),
        ('Approved', 'Approved'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    record_link = models.URLField()
    comment = models.TextField(blank=True, null=True)
    submission_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Pending')

    class Meta:
        abstract = True

class ClassicRecordSubmission(RecordSubmission):
    level = models.ForeignKey(ClassicLevel, on_delete=models.CASCADE)
    record_percentage = models.PositiveIntegerField(validators=[MaxValueValidator(100)])

    class Meta:
        verbose_name = "Classic Record Submission"
        verbose_name_plural = "Classic Record Submissions"

class PlatformerRecordSubmission(RecordSubmission):
    level = models.ForeignKey(PlatformerLevel, on_delete=models.CASCADE)
    record_time = models.DurationField()

    class Meta:
        verbose_name = "Platformer Record Submission"
        verbose_name_plural = "Platformer Record Submissions"

recordsubmission/forms.py
from django import forms
from .models import ClassicRecordSubmission, PlatformerRecordSubmission
    
class ClassicRecordSubmissionForm(forms.ModelForm):
    class Meta:
        model = ClassicRecordSubmission
        fields = ['level', 'record_link', 'record_percentage', 'comment']
        widgets = {
            'level': forms.Select(attrs={'class': 'form-control'}),
            'record_link': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://youtu.be/xvFZjo5PgG0'}),
            'record_percentage': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '69%'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'hello pls accept my record i worked hard on it thx'}),
        }

    def clean_comment(self):
        comment = self.cleaned_data['comment']
        if len(comment) > 50:
            raise forms.ValidationError("Comment cannot exceed 50 characters.")
        return comment
    
    def clean_record_percentage(self):
        record_percentage = self.cleaned_data['record_percentage']
        level = self.cleaned_data.get('level')
        if level and record_percentage < level.min_completion:
            raise forms.ValidationError("Your record percentage is lower than the minimum requirement of that level.")
        return record_percentage

class PlatformerRecordSubmissionForm(forms.ModelForm):
    class Meta:
        model = PlatformerRecordSubmission
        fields = ['level', 'record_link', 'record_time', 'comment']
        widgets = {
            'level': forms.Select(attrs={'class': 'form-control'}),
            'record_link': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://youtu.be/xvFZjo5PgG0'}),
            'record_time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'HH:MM:SS.fff'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'hello pls accept my record i worked hard on it thx'}),
        }

    def clean_comment(self):
        comment = self.cleaned_data['comment']
        if len(comment) > 50:
            raise forms.ValidationError("Comment cannot exceed 50 characters.")
        return comment

recordsubmission/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ClassicRecordSubmissionForm, PlatformerRecordSubmissionForm
from .models import ClassicRecordSubmission, PlatformerRecordSubmission
from django.contrib import messages

# Create your views here.

@login_required
def submit_record(request, record_type):
    if not request.user.is_email_verified:
        messages.error(request, 'You need to activate your email in order to submit a record.')
        return redirect('player:profile', username=request.user.username)
    
    if record_type == 'classic':
        form_class = ClassicRecordSubmissionForm
    elif record_type == 'platformer':
        form_class = PlatformerRecordSubmissionForm

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            record.player = request.user
            record.save()
            messages.success(request, 'Record submitted successfully.')
            return redirect('player:profile', username=request.user.username)
    else:
        form = form_class()

    return render(request, 'recordsubmission/submitrecord.html', {'form': form, 'record_type': record_type})

@login_required
def submissions(request):
    classic_submissions = ClassicRecordSubmission.objects.filter(player=request.user)
    platformer_submissions = PlatformerRecordSubmission.objects.filter(player=request.user)
    
    context = {
        'classic_submissions': classic_submissions,
        'platformer_submissions': platformer_submissions,
    }
    
    return render(request, 'recordsubmission/submissions.html', context)

templates/recordsubmission/submissions.html
{% extends "base.html" %}
{% block title %}My Submissions{% endblock %}
{% block content %}
<div class="container">
    <h1>My Submissions</h1>
    <p class="alert alert-info" role="alert">Feel free to open a ticket in our <a href="https://discord.gg/Q8VdCKYZFS" class="text-decoration-none" target="_blank">Discord server</a> if you need assistance regarding any of your submissions.</p>
    <hr>
    <h2>Classic Record Submissions</h2>
    {% if classic_submissions %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Submission ID</th>
                    <th>Level</th>
                    <th>Record Link</th>
                    <th>Percentage</th>
                    <th>Comment</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for submission in classic_submissions %}
                    <tr>
                        <td>{{ submission.id }}</td>
                        <td>{{ submission.level.name }}</td>
                        <td><a href="{{ submission.record_link }}" target="_blank" class="btn btn-primary">YouTube</a></td>
                        <td>{{ submission.record_percentage }}%</td>
                        <td>{{ submission.comment }}</td>
                        <td>
                            <button class="btn 
                                {% if submission.status == 'Approved' %}
                                    btn-success
                                {% elif submission.status == 'Rejected' %}
                                    btn-danger
                                {% else %}
                                    btn-warning
                                {% endif %}
                            ">{{ submission.status }}</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No classic record submissions.</p>
    {% endif %}
    <hr>
    <h2>Platformer Record Submissions</h2>
    {% if platformer_submissions %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Submission ID</th>
                    <th>Level</th>
                    <th>Record Link</th>
                    <th>Time</th>
                    <th>Comment</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for submission in platformer_submissions %}
                    <tr>
                        <td>{{ submission.id }}</td>
                        <td>{{ submission.level.name }}</td>
                        <td><a href="{{ submission.record_link }}" target="_blank">{{ submission.record_link }}</a></td>
                        <td>{{ submission.record_time }}</td>
                        <td>{{ submission.comment }}</td>
                        <td>
                            <button class="btn 
                                {% if submission.status == 'Approved' %}
                                    btn-success
                                {% elif submission.status == 'Rejected' %}
                                    btn-danger
                                {% else %}
                                    btn-warning
                                {% endif %}
                            ">{{ submission.status }}</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No platformer record submissions.</p>
    {% endif %}
</div>
{% endblock %}

templates/recordsubmission/submitrecord.html
{% extends "base.html" %}
{% block title %}Submit Record{% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Submit a Record</h1>
            <div class="mb-3">
                <a href="{% url 'recordsubmission:submit_record' 'classic' %}" class="btn btn-primary">Classic Record</a>
                <a href="{% url 'recordsubmission:submit_record' 'platformer' %}" class="btn btn-primary">Platformer Record</a>
            </div>
            <hr>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="level" class="form-label">Level</label>
                    {{ form.level }}
                    {% if form.level.errors %}
                        <div class="text-danger">{{ form.level.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_record_link" class="form-label">Record Link</label>
                    {{ form.record_link }}
                    {% if form.record_link.errors %}
                        <div class="text-danger">{{ form.record_link.errors }}</div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    {% if record_type == 'classic' %}
                    <label for="id_record_percentage" class="form-label">Record Percentage</label>
                    {{ form.record_percentage }}
                    {% if form.record_percentage.errors %}
                        <div class="text-danger">{{ form.record_percentage.errors }}</div>
                    {% endif %}
                    {% elif record_type == 'platformer' %}
                    <label for="id_record_time" class="form-label">Record Time</label>
                    {{ form.record_time }}
                    {% if form.record_time.errors %}
                        <div class="text-danger">{{ form.record_time.errors }}</div>
                    {% endif %}
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_comment" class="form-label">Comment</label>
                    {{ form.comment }}
                    {% if form.comment.errors %}
                        <div class="text-danger">{{ form.comment.errors }}</div>
                    {% endif %}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            
        </div>
    </div>
</div>

{% endblock %}