TheMoroccanDemonlist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from level import views as level_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', level_views.classic_mainlist, name='home'),
    path('player/', include('player.urls')),
    path('levels/', include('level.urls')),
    path('submit/', include('recordsubmission.urls')),
    path('guidelines/', views.guidelines, name='guidelines'),
]

level/urls.py
from django.urls import path
from . import views

app_name = 'level'

urlpatterns = [
    path('<int:pk>/', views.detail, name='classic_level_detail'),
    path('classic-mainlist/', views.classic_mainlist, name='classic_mainlist'),
    path('classic-extendedlist/', views.classic_extendedlist, name='classic_extendedlist'),
    path('classic-legacylist/', views.classic_legacylist, name='classic_legacylist'),
    path('classic-stat-viewer/', views.classic_stat_viewer, name='classic_statviewer'),
    path('platformer-mainlist/', views.platformer_mainlist, name='platformer_mainlist'),
    path('platformer-stat-viewer/', views.platformer_stat_viewer, name='platformer_statviewer'),
    path('search/', views.search, name='search'),
]

player/urls.py
from django.urls import path
from . import views

app_name = 'player'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('verify-email/', views.verify_email, name='verify-email'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('edit-social-platforms/', views.edit_social_platforms, name='edit_social_platforms'),
    path('search/', views.search, name='search'),
]

level/models.py
import math
from django.db import models
from django.core.validators import MaxValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Level(models.Model):
    DIFFICULTIES = [
        ('Hard Demon', 'Hard Demon'),
        ('Insane Demon', 'Insane Demon'),
        ('Extreme Demon', 'Extreme Demon'),
    ]

    id = models.CharField(primary_key=True, max_length=255, unique=True)
    name = models.CharField(max_length=255)
    publisher = models.CharField(max_length=255)
    difficulty = models.CharField(max_length=255, choices=DIFFICULTIES, blank=True)
    youtube_link = models.URLField(blank=True)
    youtube_thumbnail = models.URLField(blank=True)
    points = models.FloatField(default=0)

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.name}"
    
class ClassicLevel(Level):
    DURATIONS = [
        ('Tiny', 'Tiny'),
        ('Short', 'Short'),
        ('Medium', 'Medium'),
        ('Long', 'Long'),
        ('XL', 'XL'),
    ]

    ranking = models.PositiveIntegerField(default=0)
    duration = models.CharField(max_length=255, choices=DURATIONS, blank=True)
    min_points = models.FloatField(default=0)
    min_completion = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)])
    first_victor = models.ForeignKey('player.Player', on_delete=models.PROTECT, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.ranking is not None:
            if self.ranking == 0 or self.ranking > 150:
                self.points = 0.0
                self.min_points = 0.0
            elif self.ranking <= 150:
                self.points = round(500 * (1 - math.log(self.ranking, 151)), 2)
                self.min_points = round((500 * (1 - math.log(self.ranking, 151))) * 1/3, 2)
        else:
            self.points = None
            self.min_points = None

        super(ClassicLevel, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Classic Level"
        verbose_name_plural = "Classic Levels"

class PlatformerLevel(Level):
    ranking = models.PositiveIntegerField(default=0)
    record_holder = models.ForeignKey('player.Player', on_delete=models.PROTECT, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.ranking is not None:
            self.points = round(500 * (1 - math.log(self.ranking, 151)), 2)
        else:
            self.points = None

        super(PlatformerLevel, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Platformer Level"
        verbose_name_plural = "Platformer Levels"

@receiver(post_save, sender=ClassicLevel)
def update_min_completion(sender, instance, **kwargs):
    if instance.ranking > 75 and instance.min_completion != 100:
        instance.min_completion = 100
        instance.save(update_fields=['min_completion'])

@receiver(post_save, sender=ClassicLevel)
def create_classic_level_record(sender, instance, created, **kwargs):
    from levelrecord.models import ClassicLevelRecord
    if created and instance.first_victor:
        player = instance.first_victor
        if instance.youtube_link:
            record_link = instance.youtube_link
            ClassicLevelRecord.objects.create(player=player, level=instance, record_percentage=100, record_link=record_link)
        else:
            ClassicLevelRecord.objects.create(player=player, level=instance, record_percentage=100)

@receiver(post_save, sender=PlatformerLevel)
def create_platformer_level_record(sender, instance, created, **kwargs):
    from levelrecord.models import PlatformerLevelRecord
    if created and instance.record_holder:
        player = instance.record_holder
        PlatformerLevelRecord.objects.create(player=player, level=instance)

level/forms.py
from django import forms

class LevelSearchForm(forms.Form):
    query = forms.CharField(max_length=255)

level/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ClassicLevel, PlatformerLevel
from region.models import Region
from player.models import Player
from .forms import LevelSearchForm
from django.urls import reverse
from django.contrib import messages

# Create your views here.

def search(request):
    staff_members = Player.objects.filter(is_staff=True)
    if request.method == 'POST':
        form = LevelSearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            classic_levels = ClassicLevel.objects.filter(name__icontains=query)
            platformer_levels = PlatformerLevel.objects.filter(name__icontains=query)
            levels = list(classic_levels) + list(platformer_levels)
            if len(levels) == 1:
                level = levels[0]
                if isinstance(level, ClassicLevel):
                    return redirect(reverse('level:classic_level_detail', args=[level.id]))
                elif isinstance(level, PlatformerLevel):
                    return redirect(reverse('level:platformer_level_detail', args=[level.id]))
            elif len(levels) == 0:
                messages.error(request, ("No level found. Please try again."))
                return redirect("level:classic_mainlist")
            else:
                context = {
                    'levels': levels,
                    'staff_members': staff_members
                }
                return render(request, 'level/search.html', context)
        else:
            form = LevelSearchForm()
            return render(request, 'level/search.html', {'form': form, 'staff_members': staff_members})

def detail(request, pk):
    if ClassicLevel.objects.filter(pk=pk).exists():
        level = get_object_or_404(ClassicLevel, pk=pk)
        total_records = level.classiclevelrecord_set.count()
        perfect_records = level.classiclevelrecord_set.filter(record_percentage=100).count()
        youtube_id = level.youtube_link.split('.be/')[-1]
        staff_members = Player.objects.filter(is_staff=True)
        context = {
            'level': level,
            'total_records': total_records,
            'perfect_records': perfect_records,
            'youtube_id': youtube_id,
            'staff_members': staff_members
        }
        return render(request, 'level/classic/detail.html', context)
    elif PlatformerLevel.objects.filter(pk=pk).exists():
        level = get_object_or_404(PlatformerLevel, pk=pk)
        total_records = level.platformerlevelrecord_set.count()
        youtube_id = level.youtube_link.split('.be/')[-1]
        staff_members = Player.objects.filter(is_staff=True)
        context = {
            'level': level,
            'total_records': total_records,
            'youtube_id': youtube_id,
            'staff_members': staff_members
        }
        return render(request, 'level/platformer/detail.html', context)

def classic_mainlist(request):
    main_levels = ClassicLevel.objects.filter(ranking__lte=75)
    staff_members = Player.objects.filter(is_staff=True)
    context = {
        'main_levels': main_levels,
        'staff_members': staff_members
    }
    return render(request, 'level/classic/mainlist.html', context)

def classic_extendedlist(request):
    extended_levels = ClassicLevel.objects.filter(ranking__range=(76, 150))
    staff_members = Player.objects.filter(is_staff=True)
    context = {
        'extended_levels': extended_levels,
        'staff_members': staff_members
    }
    return render(request, 'level/classic/extendedlist.html', context)

def classic_legacylist(request):
    legacy_levels = ClassicLevel.objects.filter(ranking__gt=150)
    staff_members = Player.objects.filter(is_staff=True)
    context = {
        'legacy_levels': legacy_levels,
        'staff_members': staff_members
    }
    return render(request, 'level/classic/legacylist.html', context)

def classic_stat_viewer(request):
    regions = Region.objects.all()
    for region in regions:
        region.players = Player.objects.filter(region=region)
    return render(request, 'level/classic/statviewer.html', {'regions': regions})

def platformer_mainlist(request):
    main_levels = PlatformerLevel.objects.filter(ranking__lte=75)
    staff_members = Player.objects.filter(is_staff=True)
    context = {
        'main_levels': main_levels,
        'staff_members': staff_members
    }
    return render(request, 'level/platformer/mainlist.html', context)

def platformer_stat_viewer(request):
    regions = Region.objects.all()
    for region in regions:
        region.players = Player.objects.filter(region=region)
    return render(request, 'level/platformer/statviewer.html', {'regions': regions})

templates/level/platformer/detail.html
{% extends "base.html" %}
{% block title %}{{ level.name }} details{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h2>{{ level.name }}, by {{ level.publisher }}</h2>
                </div>
                <div class="card-body text-center">
                    <div style="aspect-ratio: 16/9; padding: 0;">
                        <iframe class="embed-responsive-item w-100" src="https://www.youtube.com/embed/{{ youtube_id }}" style="height:100%;" allowfullscreen></iframe>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <p><strong>Level ID:</strong> {{ level.id }}</p>
                            <p><strong>Difficulty:</strong> {{ level.get_difficulty_display }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Ranking:</strong> {{ level.ranking }}</p>
                            <p><strong>Points:</strong> {{ level.points }}</p>
                        </div>
                    </div>
                    <h3 class="mt-4">Records:</h3>
                    <p>Total Records: {{ total_records }}</p>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Player</th>
                                    <th scope="col">Record Time</th>
                                    <th scope="col">YouTube Link</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for record in level.platformerlevelrecord_set.all %}
                                    <tr>
                                        <td><a href="{% url 'player:profile' record.player.username %}" style="color: inherit;" class="text-decoration-none">{{ record.player.username }}</a></td>
                                        <td>{{ record.record_time }}</td>
                                        <td>
                                            <a class="btn btn-outline-primary btn-sm" href="{{ record.record_link }}" target="_blank">YouTube</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header text-center">
                    <h3>List editors</h3>
                </div>
                <div class="card-body text-center">
                    <p>Contact any of these people if you need assistance regarding the list.</p>
                    {% for staff_member in staff_members %}
                        <a class="text-decoration-none fw-bold" style="color: inherit;" href="{% url 'player:profile' staff_member.username %}">{{ staff_member }}</a>{% if not forloop.last %} - {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-header text-center">
                    <h3>Guidelines</h3>
                </div>
                <div class="card-body text-center">
                    <p>Before any submission please consider checking the guidelines for the list. Any submission that does not follow the guidelines will be rejected.</p>
                    <a href="{% url 'guidelines' %}" class="btn btn-primary w-75">Read the guidelines</a>
                </div>
            </div>
            <div class="card mt-3">
                <iframe src="https://discord.com/widget?id=1144377634831220847&theme=dark" class="w-100" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/level/platformer/mainlist.html
{% extends "base.html" %}
{% block title %}Platformer Main List{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% for level in main_levels|dictsort:"ranking" %}
                <div class="card mt-3 mx-auto{% if forloop.last %} mb-3{% endif %}" style="width: 780px; max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <a href="{{ level.youtube_link }}" target="_blank">
                                <img src="{{ level.youtube_thumbnail }}" class="img-fluid rounded-start" style="width: 100%;">
                            </a>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a class="text-decoration-none" style="cursor: pointer; color: inherit;" href="{% url 'level:classic_level_detail' level.id %}">
                                        #{{ level.ranking }} - {{ level.name }}
                                    </a>
                                </h5>
                                <p class="card-text"><strong>Published by:</strong> {{ level.publisher }}</p>
                                <button type="button" class="btn btn-primary"  data-bs-placement="right" data-bs-content="Copied to clipboard!" data-bs-toggle="popover" data-bs-container="body" data-level-id="{{ level.id }}" id="liveAlertBtn">Copy Level ID</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-header text-center">
                    <h3>List editors</h3>
                </div>
                <div class="card-body text-center">
                    <p>Contact any of these people if you need assistance regarding the list.</p>
                    {% for staff_member in staff_members %}
                        <a class="text-decoration-none fw-bold" style="color: inherit;" href="{% url 'player:profile' staff_member.username %}">{{ staff_member }}</a>{% if not forloop.last %} - {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header text-center">
                    <h3>Guidelines</h3>
                </div>
                <div class="card-body text-center">
                    <p>Before any submission please consider checking the guidelines for the list. Any submission that does not follow the guidelines will be rejected.</p>
                    <a href="{% url 'guidelines' %}" class="btn btn-primary w-75">Read the guidelines</a>
                </div>
            </div>

            <div class="card mt-3">
                <iframe src="https://discord.com/widget?id=1144377634831220847&theme=dark" class="w-100" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
            </div>
        </div>
    </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl, {
    delay: { "show": 0, "hide": 2000 }
  }));
  var copyButtons = document.querySelectorAll(".btn");
    copyButtons.forEach(function (button) {
        button.addEventListener("click", function () {
          var id = button.getAttribute("data-level-id");
          copyToClipboardAndShowPopover(button, id);
      });
    });
  });

  function copyToClipboard(text) {
    var textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
  }

  function copyToClipboardAndShowPopover(element, text) {
    copyToClipboard(text);
    const popover = bootstrap.Popover.getInstance(element);
    popover.show();
    setTimeout(() => {
      popover.hide();
    }, 2000);
  }
</script>
{% endblock %}

templates/level/platformer/statviewer.html
{% extends "base.html" %}
{% load static %}
{% block title %}Platformer Stat Viewer{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="map-section">
                <div style="min-height:696px">
                    <script type="text/javascript" defer src="https://datawrapper.dwcdn.net/xCkE3/embed.js?v=9" charset="utf-8"></script>
                    <noscript><img src="https://datawrapper.dwcdn.net/xCkE3/full.png" alt="" /></noscript>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <form class="d-flex mb-3" role="search" method="post" action="{% url 'player:search' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search for a player" aria-label="Search" name="query">
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
            <div class="accordion ml-5">
                {% for region in regions|dictsortreversed:"classic_points" %}
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne{{region.id}}" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                                {{region}}
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseOne{{region.id}}" class="accordion-collapse collapse">
                            <div class="accordion-body">
                                {% for player in region.players|dictsortreversed:"platformer_points" %}
                                    <p>{{ player.username }} - {{ player.platformer_points|floatformat:"2"}} points</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}