TheMoroccanDemonlist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from level import views as level_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', level_views.classic_mainlist, name='home'),
    path('player/', include('player.urls')),
    path('levels/', include('level.urls')),
    path('submit/', include('recordsubmission.urls')),
    path('guidelines/', views.guidelines, name='guidelines'),
]

level/urls.py
from django.urls import path
from . import views

app_name = 'level'

urlpatterns = [
    path('<int:pk>/', views.detail, name='classic_level_detail'),
    path('classic-mainlist/', views.classic_mainlist, name='classic_mainlist'),
    path('classic-extendedlist/', views.classic_extendedlist, name='classic_extendedlist'),
    path('classic-legacylist/', views.classic_legacylist, name='classic_legacylist'),
    path('classic-stat-viewer/', views.classic_stat_viewer, name='classic_statviewer'),
    path('platformer-mainlist/', views.platformer_mainlist, name='platformer_mainlist'),
    path('platformer-stat-viewer/', views.platformer_stat_viewer, name='platformer_statviewer'),
    path('search/', views.search, name='search'),
]

player/urls.py
from django.urls import path
from . import views

app_name = 'player'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('verify-email/', views.verify_email, name='verify-email'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('edit-social-platforms/', views.edit_social_platforms, name='edit_social_platforms'),
    path('search/', views.search, name='search'),
]

recordsubmission/urls.py
from django.urls import path
from . import views

app_name = 'recordsubmission'

urlpatterns = [
    path('submit-record/<str:record_type>/', views.submit_record, name='submit_record'),
    path('submissions/', views.submissions, name='submissions'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2420440188706311" crossorigin="anonymous"></script>
</head>

<style>
body {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
}
    
.content {
flex-grow: 1;
}
    
footer {
flex-shrink: 0;
}
</style>
<body data-bs-theme="light" class="page-layout">
    <nav class="navbar navbar-expand-lg bg-body-tertiary shadow-lg">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="{% url 'home' %}">TMDL.</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Classic Demonlist
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'level:classic_mainlist' %}">Main list</a></li>
                            <li><a class="dropdown-item" href="{% url 'level:classic_extendedlist' %}">Extended list</a></li>
                            <li><a class="dropdown-item" href="{% url 'level:classic_legacylist' %}">Legacy list</a></li>
                            <li><a class="dropdown-item" href="{% url 'level:classic_statviewer' %}">Stat Viewer</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Platformer Demonlist
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'level:platformer_mainlist' %}">Main list</a></li>
                            <li><a class="dropdown-item disabled" href="#">Extended list</a></li>
                            <li><a class="dropdown-item disabled" href="#">Legacy list</a></li>
                            <li><a class="dropdown-item" href="{% url 'level:platformer_statviewer' %}">Stat Viewer</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'guidelines' %}">Guidelines</a>
                    </li>
                </ul>
                <form class="d-flex mx-auto" role="search" method="post" action="{% url 'level:search' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search for a level" aria-label="Search" name="query">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{% url 'player:profile' request.user.username %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'recordsubmission:submissions' %}">My submissions</a></li>
                            <li><a class="dropdown-item" href="{% url 'recordsubmission:submit_record' 'classic' %}">Submit a record</a></li>
                            <li><a class="dropdown-item" href="{% url 'player:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-item btn btn-primary" href="{% url 'player:login' %}">Log in</a>
                    </li>
                    <li class="nav-item ms-1">
                        <a class="nav-item btn btn-primary" href="{% url 'player:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container mt-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    </div>

<div class="content">
    {% block content %}
    {% endblock %}
</div>
<footer class="bg-body-tertiary text-center text-lg-start mt-3 shadow-lg">
    <div class="text-center p-3">
        Made by <a class="text-body fw-bold text-decoration-none" href="https://github.com/apostorial" target="_blank">Apostorial</a>
        <br>
        <a class="text-body fw-bold text-decoration-none" href="{% url 'home' %}">TheMoroccanDemonlist</a> is not affiliated with RobTopGames.
        <hr>
        Feel free to contribute to the website on <a class="text-body fw-bold text-decoration-none" href="https://github.com/apostorial/TheMoroccanDemonlist" target="_blank">GitHub</a> (The code is bad pls help)
    </div>
</footer>
<script>
    function setTheme() {
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme) {
            document.body.setAttribute('data-bs-theme', savedTheme);
            if (savedTheme === 'light') {
                document.getElementById('lightTheme').checked = true;
            } else {
                document.getElementById('darkTheme').checked = true;
            }
        }
    }

    function handleThemeChange() {
        const lightThemeRadio = document.getElementById('lightTheme');
        const darkThemeRadio = document.getElementById('darkTheme');

        lightThemeRadio.addEventListener('change', () => {
            localStorage.setItem('theme', 'light');
            document.body.setAttribute('data-bs-theme', 'light');
        });

        darkThemeRadio.addEventListener('change', () => {
            localStorage.setItem('theme', 'dark');
            document.body.setAttribute('data-bs-theme', 'dark');
        });
    }

    document.addEventListener('DOMContentLoaded', () => {
        setTheme();
        handleThemeChange();
    });
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4811306720061580" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/guidelines.html
{% extends "base.html" %}
{% load static %}
{% block title %}Guidelines{% endblock %}
{% block content %}
<div class="container mx-auto mb-3">
    <div class="row">
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Allowed Hacks</h5>
                    <ul>
                        <li>FPS bypass up to 360FPS, same goes for TPS bypass</li>
                        <li>Show hitboxes on death, only for non memory levels</li>
                        <li>Speedhack only x1.1+</li>
                        <li>Zero delay</li>
                        <li>Smart StartPos</li>
                        <li>No wave pulse</li>
                        <li>No death effect</li>
                        <li>No respawn pulse</li>
                        <li>Trail always on/off</li>
                    </ul>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Banning Players</h5>
                    <ul>
                        <li>A flag role in the Discord will be given to hackers, a flagged player will go through more severe hack detection and will be obligated to provide more proof</li>
                        <li>If a player has been caught hacking a second time they will be banned for a duration from 2 weeks to 2 months</li>
                        <li>If a player has been caught hacking a third time they will be banned permanently</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Record Submitting</h5>
                    <ul>
                        <li>Extremes demon completions require audible clicks</li>
                        <li>Insane demons in the top 75 hardest insanes (visit the idl) require audible clicks</li>
                        <li>2 player levels will require a recording with a hand cam</li>
                        <li>Cheat indicator must always be on, rule doesn't apply to users without MegaHackPro</li>
                        <li>The recording must be of clear quality</li>
                        <li>The recording must be submitted on our <a class="text-decoration-none" href="https://discord.gg/CfzT9EQpr2" target="_blank">Discord server</a></li>
                    </ul>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Bonus</h5>
                    <ul>
                        <li>1 attempt practice completions are allowed</li>
                        <li>100% accuracy runs <strong>won't</strong> be accepted.</li>
                        <li>Exiting at the endscreen <strong>won't</strong> count as a completion and the record will not be accepted</li>
                        <li>If a level has been beaten on an external LDM that's not supported by the list the record <strong>won't</strong> be accepted</li>
                        <li>Using a StartPos from 0% is allowed</li>
                    </ul>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Unauthorized mods</h5>
                    <ul>
                        <li>CBF Mod (Click Between Frames)</li>
                        
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

{% endblock %}